src/extension.ts, src/formatter.ts
adds DocumentRangeFormattingEditProvider conformance to Formatter, to support selection formatting
=> adds format selection support

src/brightScriptDebugSession.spec.ts, src/brightScriptDebugSession.ts
=> Disable breakpoints set during active debug session.

package-lock.json, package.json
=> Upgraded to brightscript-formatter@1.4.0.

CHANGELOG.md, README.md, package-lock.json, package.json
Bumped version to 1.3.0 and updated the docs to show new features.
=> Version bump and Update docs

.travis.yml, .vscode/settings.json, README.md, developer-guidelines.md, package-lock.json, package.json, src/RokuAdapter.ts, src/brightScriptDebugSession.spec.ts, src/brightScriptDebugSession.ts, src/commands.ts, src/completion.ts, src/debugAdapter.ts, src/declaration.ts, src/definitionProvider.ts, src/extension.ts, src/formatter.ts, src/symbol.ts, src/symbolProvider.ts, src/tsconfig.json, src/tslint.json, src/util.ts
Fail the build if tslint fails.
Added draft developers guide with some of the top standards.
Formatted all files according to the new tslint standard.
=> start enforcing coding standards

package.json, src/LogOutputManager.spec.ts, src/LogOutputManager.ts, src/extension.ts, src/mockVscode.spec.ts
adds command for clearing output
moves DebugErroHandler to LogOutputManager
=> Add ability to mark log output

syntaxes/brightscript.tmLanguage.json
Updated textmate grammar.
Fixes #103
=> Update textmate grammar

src/BrightScriptDebugSession.ts, src/DebugConfigurationProvider.ts, src/util.ts
=> Support for conditional breakpoints

package.json
Clean up spelling and description text
=> Description text clean up

package-lock.json, package.json, src/BrightScriptDebugSession.ts, src/DebugConfigurationProvider.ts
=> Run screen saver entrypoint check

src/RokuAdapter.ts
Fixes bug in the debugger that would cause an unhandled crash when evaluating a roList.
=> Fix bug that would crash debugger when evaluating roList

README.md, package-lock.json, package.json, src/BrightScriptDebugSession.ts, src/ComponentLibraryServer.ts, src/DebugConfigurationProvider.ts
This is very early support for component libraries. I am interested in feedback as this is the first time I have worked on static file hosting and file manipulation.
=> Component library support

README.md, package.json, src/BrightScriptDebugSession.spec.ts, src/BrightScriptDebugSession.ts, src/DebugConfigurationProvider.ts
Allows users to change existing bs_consts in the channel manifest to change channel behaviour or features with the launch configs.
=> Bs_const support in launch configs

.vscode/settings.json, README.md, package-lock.json, package.json, src/BrightScriptDebugSession.ts, src/DebugConfigurationProvider.ts, src/LogOutputManager.ts, src/PrintedObjectParser.spec.ts, src/PrintedObjectParser.ts, src/RokuAdapter.spec.ts, src/RokuAdapter.ts, src/tslint.json, src/util.spec.ts, src/util.ts
Fixes #152. This changes the way all object hover/identify prints are sent to the Roku, but I believe it's more stable.
=> Fix large arrays

package-lock.json, package.json, src/ComponentLibraryServer.ts, src/util.spec.ts, src/util.ts
=> Added "port in use" message when component library hosting crashes

src/BrightScriptDebugSession.ts
Cache the function names in their original case instead of reading the file on every request. 
Th reduces the stacktrace debug-server request by around 9 milliseconds on my machine. Not a lot, but every little bit counts. I imagine this would be more beneficial to developers who aren't using an SSD.
=> Cache function names in their original case.

package.json
Updated the files array schema to match the normal package files array.
=> correct-files-array-schima-for-component-libraries

src/BrightScriptDebugSession.ts
Optimize component library file renaming by only running the regex once on every brs file appending the comp lib postfix
=> Optimize component library file renaming

src/BrightScriptDebugSession.ts
Speed up RALE insertion by using replace in file instead and doing non regex based lookup
=> Speed up RALE insertion

.vscode/launch.json, CHANGELOG.md, README.md, package.json, src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts, src/LogOutputManager.ts
Fixes #216 by adding logfilePath property.
=> write output to file

README.md, snippets/brighterscript.json
Also fixes some typos regarding snippets in README
=> Fixes snippet warning when debugging extension

src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts
TODO:
- Add some tests for the `processEnvFile` function
=> Fixed an issue where some env options could be skipped

CHANGELOG.md, README.md, package-lock.json, package.json, src/formatter.ts
Adds support for loading bsfmt.json formatter options. If `bsfmt.json` exists, all formatter-related user/workspace settings will be ignored. 
Fixes #270.
=> bsfmt.json

src/DeclarationProvider.ts, src/LogDocumentLinkProvider.spec.ts, src/LogDocumentLinkProvider.ts, src/LogOutputManager.spec.ts, src/LogOutputManager.ts
Wouldn't mind a preliminary look at this; if we really need, I can add some additional unit tests; but I know it's not borked, coz I'm using it heavily
=> Adds support for logouput format options for link:// style links

language-configuration.json, src/autoIndent.spec.ts, test/autoIndent/case1.brs, test/autoIndent/case2.brs
Automatic increase/decrease indent for common statements
```brightscript
function autoIndent(arg as Object) as void 'indent
if (cond) then 'indent
print "has cond"; cond
if cond2 then print "has cond2"; cond2 'don't indent
else if cond2 'decrease, indent
print "cond2"; cond2
else 'decrease, indent
print "not cond"; cond
end if 'decrease
p = { 'indent
x: 100
y: 100
} 'decrease
fn = sub() 'indent
print "is fn"
end sub 'decrease
for i=0 to 10 'indent
print "i="; i
endfor 'decrease
end function 'decrease
```
Fixes #263
=> Auto-indent configuration

src/DebugConfigurationProvider.ts
Forces deploy staging path to resolve potential conflicts with bsconfig.json
see also: https://github.com/rokucommunity/roku-debug/pull/18
=> Force deploy staging path

language-configuration.json, syntaxes/brightscript.tmLanguage.json
Add try/catch syntax highlighting and indentation logic.
=> Try catch enhancements

package-lock.json, package.json, src/LogOutputManager.ts, src/extension.spec.ts, src/extension.ts, src/mockVscode.spec.ts
dependent on https://github.com/rokucommunity/roku-debug/pull/28
=> chanperf support

README.md, package-lock.json, package.json, src/BrightScriptCommands.ts, src/DebugConfigurationProvider.ts, src/SceneGraphDebugCommands.ts, src/extension.ts
Dependent on changes in roku-debug: https://github.com/rokucommunity/roku-debug/pull/29
=> Basic scenegraph debug command support

src/SceneGraphDebugCommands.ts
Fixed an issue where some sg debug command logs missing results for large responses.
=> Fixed sg debug command logs missing results for large responses.

.github/workflows/build.yml, package-lock.json, package.json, src/LanguageServerManager.ts, src/mockVscode.spec.ts
Upgrade to languageclient version 7. 
upgrade node version in CI.
=> Upgrade to languageclient v7

package.json, src/SceneGraphDebugCommands.ts
=> Fixed an issue with the genkey and showkey commands

syntaxes/brightscript.tmLanguage.json
=> Fix syntax highlight issue for `step`

src/LogOutputManager.spec.ts, src/LogOutputManager.ts
Refactor the log filtering function to have an easier logic flow.
=> Simplify log filtering logic

package-lock.json, package.json, src/grammar/brightscript.tmLanguage.spec.ts, src/grammar/grammerTestHelpers.spec.ts, src/mockVscode.spec.ts
Adds support for in-code grammar testing of our brightscript textmate file.
=> Adds testmate grammar testing

src/DeclarationProvider.ts, src/util.ts
https://github.com/rokucommunity/vscode-brightscript-language/issues/267
=> Excludes the out directory from readDeclarations function

package-lock.json, package.json, src/ActiveDeviceManager.ts, src/BrightScriptCommands.spec.ts, src/BrightScriptCommands.ts, src/extension.ts
Adds a "Refresh" button to the devices list.
=> Add a "refresh" button in the Devices panel

src/LogOutputManager.ts, ui/rdb/ChangedFieldEntry.ts, ui/rdb/ExtensionIntermediary.ts, ui/rdb/components/SceneGraphInspectorPanel/NodeBranchView.svelte, ui/rdb/components/SceneGraphInspectorPanel/NodeDetailView.svelte, ui/rdb/views/SceneGraphInspectorPanel.svelte
See commit messages for a list of what all what was done as a part of this PR
https://user-images.githubusercontent.com/1753881/177899012-e9fbad03-d9d2-469a-8614-783f32b1cd16.mov
.
=> Rdb improvements

src/LogOutputManager.ts
Allow the debug session to show popups to the user. 
Related: https://github.com/rokucommunity/roku-debug/pull/90
=> Support showing popups from debug sessions

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
=> Fix component var coloring

docs/Editing/word-separators.md
=> Document customizing editor.wordSeparators for trailing type symbols

package-lock.json, package.json, src/DebugConfigurationProvider.ts, src/extension.spec.ts, src/extension.ts, src/mockVscode.spec.ts, src/viewProviders/BaseRdbViewProvider.ts, src/viewProviders/BaseWebviewViewProvider.ts, src/viewProviders/RokuCommandsViewProvider.ts, src/viewProviders/RokuRegistryViewProvider.spec.ts, src/viewProviders/RokuRegistryViewProvider.ts, webviews/src/ExtensionIntermediary.ts, webviews/src/shared/OdcSetManualIpAddress.svelte, webviews/src/shared/OdcSetupSteps.svelte, webviews/src/views/RokuCommandsView/RokuCommandsView.svelte, webviews/src/views/RokuRegistryView/RokuRegistryView.svelte, webviews/src/views/SceneGraphInspectorView/NodeBranchPage.svelte, webviews/src/views/SceneGraphInspectorView/NodeDetailPage.svelte, webviews/src/views/SceneGraphInspectorView/SceneGraphInspectorView.svelte, webviews/src/views/SceneGraphInspectorView/SettingsPage.svelte
- upgrade roku-test-automation module and update code accordingly, 
- remove information on hover, 
- default including ArrayGrid children to true, 
- switch to showing RDB views always and allow manual ip address entry,
- add ability to retrieve key path info for node,  
- update Roku Registry view to properly import and export,
- add clear and refresh buttons as well
=> upgrade roku-test-automation module and update code accordingly

package-lock.json, package.json, src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
- Fixes syntax highlighting for interface fields with trailing comments
- fixes syntax highlighting for interface functions
**Before:** 
**After:**
=> Fix iface syntax highlighting for comments & funcs

src/LogOutputManager.spec.ts, src/LogOutputManager.ts, src/extension.ts, src/managers/DiagnosticManager.ts
Refine the diagnostics handling during debug sessions
=> Diagnostic manager

package.json, src/BrightScriptCommands.ts, src/DebugConfigurationProvider.ts, src/commands/CaptureScreenshotCommand.ts, src/viewProviders/OnlineDevicesViewProvider.ts
1. Ability to add support for "capture screenshot" through command palette and device view.
2. Upon success - screenshot preview is shown to user
Detailed issue: https://github.com/rokucommunity/vscode-brightscript-language/issues/430
=> Add ability to capture device screenshots

package-lock.json, package.json, src/extension.ts
Make undent a prod dependency to prevent the extension from crashing.
=> Fix extension crash in 2.45.0

package-lock.json, package.json, scripts/releases.ts, src/ActiveDeviceManager.ts, src/util.ts
- remove the custom fetching of device-info in favor of the `rokuDeploy.getDeviceInfo()` function. 
- fixes a few typescript and npm dependency issues
=> Use getDeviceInfo from roku-deploy

webviews/src/ExtensionIntermediary.ts, webviews/src/views/SceneGraphInspectorView/Branch.svelte
=> Add support for focusing a node in SceneGraph Inspector

package-lock.json, package.json, src/managers/WebviewViewProviderManager.ts, src/viewProviders/BaseRdbViewProvider.ts, src/viewProviders/BaseWebviewViewProvider.ts, src/viewProviders/RokuAppOverlaysViewViewProvider.ts, src/viewProviders/RokuAutomationViewViewProvider.ts, src/viewProviders/RokuDeviceViewViewProvider.ts, src/viewProviders/RokuFileSystemViewViewProvider.ts, src/viewProviders/RokuReplViewProvider.ts, src/viewProviders/SceneGraphInspectorViewProvider.ts, src/viewProviders/ViewProviderCommand.ts, src/viewProviders/ViewProviderId.ts, webviews/src/ExtensionIntermediary.ts, webviews/src/main.ts, webviews/src/views/RokuDeviceView/RokuDeviceView.svelte, webviews/src/views/RokuReplView/RokuReplView.svelte
=> Add on device brightscript repl

src/viewProviders/RokuDeviceViewViewProvider.ts, webviews/src/shared/OdcSetManualIpAddress.svelte
Fixes broken device view.
Improves the manual IP address UI layout.
**Before:**
**After:**
=> Fix broken device view and Improve manual ip address component

.github/workflows/create-vsix.yml
Fix create-vsix by upgrading to upload-artifact@v4
=> Fix create-vsix

package-lock.json, package.json, src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Color the `m.top` and `m.global` objects like `m` (darker blue in the default dark vscode theme). 
**Before:**
**After:**
=> Highlight `m.top` like `m`.

package-lock.json, package.json, src/LanguageServerManager.spec.ts, src/LanguageServerManager.ts
Shows progress from the lsp busy status in the tooltip multi-line. This _should_ be backwards compatible with the existing status, but it also supports the `scope` property (mostly used to include project name). 
Looks like this:
=> Show multi-line lsp progress details
