rokucommunity/vscode-brightscript-language

package-lock.json, package.json, src/commands.ts, src/completion.ts, src/declaration.ts, src/definitionProvider.ts, src/extension.ts, src/symbol.ts, src/symbolProvider.ts, src/util.ts
Hi, here's a preliminary PR so you can try out the language features for yourself.
- adds declarations and symbols
- adds go to definition support
- adds command to jump between xml and brs files
- adds placeholder for completion
Please note - I formatted extension.ts (by accident); but I figured  I'll leave it as is, as it's more consistent : I can back it out if needs be.
Fire it up, press APPLE+SHIFT+O, to view symbols in file APPLE-T for whole project, and F12 to go to defintion.
Also find command to switch between xml and brs files - you can assign a hotkey to Brightscript: Toggle xml/brs
=> additional brightscript navigation features

package.json, syntaxes/brightscript.tmLanguage.json
**Included 'step' as reserved word:**
According to [Roku SDK Docs](https://sdkdocs.roku.com/display/sdkdoc/Program+Statements) `step` is an optional part of `for` loops to specify the increment after each iteration.
**Added 'not searchViewletVisible' as condition for keybindings**
`searchViewletVisible` is the name of the search widget if it's part of the panel instead of the sidebar. Without this condition it's practically impossible to use the search panel.
=> Included 'step' as reserved word. Added 'not searchViewletVisible' as condition for keybindings.

package.json
When running the branch `feature/language-server`, I got errors about the `vscode-languageserver` module not being found. By moving it from `devDependencies` to dependencies`, it seems to be working correctly.
=> `vscode-languageserver` is required for usage as well as development

CHANGELOG.md, src/BrightScriptDebugSession.ts, src/RokuAdapter.ts
Certain launch errors are not properly captured in the promise or async/await chains, and as such, the debugger doesn't stop, or dies without a good error. This PR fixes many of these issues by doing a better job passing the errors up the chain, and showing a proper error message.
Fixes #69
=> Bubble launch failure errors to top level so they can show in UI. (Fixes #69)

src/BrightScriptDebugSession.ts, src/RokuAdapter.ts
This attempts to close any leftover debugging threads before side loading and when stopping the debug adapter.
=> Close any leftover debugging threads before side loading

src/RokuAdapter.ts
This was related to using `exec` with a `g` flag. See the following from the docs:
If your regular expression uses the "g" flag, you can use the exec() method multiple times to find successive matches in the same string. When you do so, the search starts at the substring of str specified by the regular expression's lastIndex property (test() will also advance the lastIndex property).  Note that the lastIndex property will not be reset when searching a different string it will start its search at its existing lastIndex .
=> High level objects not always parsed correctly

README.md, package.json, src/BrightScriptDebugSession.spec.ts, src/BrightScriptDebugSession.ts, src/DebugConfigurationProvider.ts, src/LogDocumentLinkProvider.ts
Multiple source directory support 
- Depreciates debugrootDir string and replaces it with sourceDirs array to support multiple source directories. 
- Fires error when debugrootDir is used in the launch and prompts the user to update to sourceDirs.
- Removed all remaining breakpoints after looping through them to prevent crash on a breakpoint existing in the workspace but out of scope
=> Multiple source directory support 

src/LogOutputManager.ts
If a breakpoint is hit - and the app stops (e.g. a runtime error, or breakpoint then app quit), and breakpoint continuation is enabled, then in most cases, logoutput will stop making it's way to the brightscript log.
This pr fixes that problem; by resetting these flags on launch.
=> resets microdebugger and next breakpoint flags

README.md, package.json, src/BrightScriptDebugSession.spec.ts, src/BrightScriptDebugSession.ts, src/DebugConfigurationProvider.ts, src/mockVscode.spec.ts, syntaxes/brightscript.tmLanguage.json
The goal of this PR is to allow users to manage their version of the tracker task across all channels. This way the tracker task code is not committed to their channel repo and so that when the tracker task and desktop RALE app is updated they only need to update it in the one location.
=> Tracker task injection on launch

src/BrightScriptDebugSession.ts, src/ComponentLibraryServer.ts
Fixed an issue where every port was being flagged as is use in the ComponentLibraryServer.
Related to issue #204 and pr #205
=> fix-to-port-in-use-detection

src/DeclarationProvider.ts, src/DefinitionRepository.ts
I've been using this code for several months now; it's just as shoe-string as the rest of the impl; but it does get method feedback and navigation support for common bs use cases, like namespaces, extends, classes, and constructors.
=> feat(DeclarationProvider): Adds temporary support for brighterscript symbol detection and navigation

src/DebugConfigurationProvider.ts
Now handles all env variable replacements for launch.json configs.
Even if you use them in your `bsconfig.json` file they will replace - which is a nice side effect for some of the projects I'm part of right now actually.
I left the existing piece that was setting default values based on config keys that you put in the env file but I'm not sure how applicable that is so you can let me know if that needs to just get scrapped now.
Let me know if anything sounds like it might break something else but it appears to be working as intended as of right now.
=> Enables replacement of all ${env:VARIABLE} replacements

src/LogOutputManager.ts
Extensions would internally silently crash when `roku-debug` sends a message with a text body instead of an array of errors.
Thankfully without consequence, but the code isn't very defensive.
=> Prevent (hidden) runtime exception

syntaxes/brightscript.tmLanguage.json
Adds proper syntax highlighting for template strings. 
I moved the top-level definitions into a named repository item, so that way it can be referenced from multiple other locations. that's why the majority of the churn is there.
=> Add proper template string syntax highlighting

src/LogDocumentLinkProvider.ts, src/extension.ts, src/mockVscode.spec.ts
This pr fixes the issue here: https://github.com/microsoft/vscode/issues/81520
This has likely _always_ been broken, while I've been in click happy link bliss on ubuntu/mac.
I use @TwitchBronBron suggested fix here, of registering a link provider, works perfect, as the gif attests:
=> fixes broken document links on windows.

package.json, src/LanguageServerManager.ts, src/extension.ts
Adds command to restart the language server from within vscode. This eliminates the need to completely reload vscode.
=> Add command to restart language server

syntaxes/brightscript.tmLanguage.json
Removes scenegraph-specific syntax tokenization. These can be handled by the other matchers. (this grammar was inherited so this was just a holdover from the previous author). 
Fixes #297
=> Remove scenegraph support function colorization

package.json, src/extension.ts, src/util.ts
Adds better logging support for tracking issues within the extension and its dependencies (i.e. roku-debug, roku-deploy, etc...). 
Changes:
- add `brightscript.extensionLogfilePath` setting to specify an output file for debug logs
- add `logLevel` debug parameter info for launch.json
- rename `SceneGraph Debug Commands Log` output panel to `SceneGraph Debug Commands`
- rename `BrightScript Debug Server` output panel to `BrightScript Extension` for wider usage.
=> Better logging

syntaxes/brightscript.tmLanguage.json
- Add better syntax highlighting for interface statements. 
- add `type_declaration` pattern which will help reduce duplicate syntaxes in the future. (view it [here](https://github.com/rokucommunity/vscode-brightscript-language/commit/2924bbf852ef60388b6a126f55491815c1c16e6d#diff-33a1f0acec8bb993dcfdb3e0b3405f62eb21db0ab3ae6b41170687692091b89fR490))
Before:
After:
=> Better interface statement syntax highlighting.

src/commands/LanguageServerInfoCommand.ts
- Improves wording around the "Pick which version of brighterscript language server you want to use" menu option.
- adds second entry in the menu (restart language server) to make it more clear that you need to pick the other option to change the language server version. 
Here's the new design: 
https://user-images.githubusercontent.com/2544493/152199358-211f8c75-4e59-4edc-8fea-951f197e8d97.mp4
=> Improve wording for bsc picker. Add bsc restart command

syntaxes/brightscript.tmLanguage.json
Fixes bug where interfaces weren't colored properly when indented.
Before:
After:
=> Fix colorization with interfaces inside namespaces

syntaxes/brightscript.tmLanguage.json
Combines the various primitive literal expressions into a single pattern since they never need to be referenced individually. 
This is just a housekeeping PR, no new functionality.
=> Merge primitive literal exprs into single lib pattern

src/commands/LanguageServerInfoCommand.ts, syntaxes/brightscript.tmLanguage.json
Adds enum syntax highlighting. Depends on #358 
Example:
=> Add enum syntax highlighting

package-lock.json, package.json, src/LogOutputManager.spec.ts, src/LogOutputManager.ts, tsconfig.json
the mocha-param library makes unit tests a little harder to debug. Removed it in favor of a helper test function with explicit calls.
Fixed a small bug with log line numbers not being properly detected.
=> Remove mocha param

src/BrightScriptCommands.ts, src/util.ts
The app times out when too large of a keypress is sent. This resolves that issue by just using the http remote presses. (I don't remember why we switched away from it. here goes nothing!)
=> Fix sendRemoteText timeout bug

package.json
Contributes brighterscript problem matchers to make brighterscript preLaunchTasks easier to use.
- `$bsc` is for single-run builds
- `$bsc-watch` is for matching brighterscript problems when in watch mode. Useful for background tasks. 
- `$bsc-watch-silent` is for detecting the start/stop status of brighterscript watch tasks, but intentionally does not match match any emitted diagnostics. This prevents duplicate diagnostics showing up along side the language server diagnostics.
=> Add bsc problem matchers

src/managers/RemoteControlManager.ts
Fixes a quirk that, whenever the Remote Control Mode statusbar item is clicked, it would retain focus. Then, when a user would press the `enter` key, it would act like a "click" on the statusbar item and disable **remote control mode**. 
To fix this, after the item is clicked, we focus the active editor. If there is no active editor, then we execute a few workspace commands to toggle through active editor groups. Since there are no active editor groups when there's no active editor, it removes focus to the statusbar item without any negative side effects.
One downside to this is that I can't really know what else to focus on. For example, if you have the terminal focused, this will technically lose focus on the terminal. However, since you clicked a statusbar item, you already moved the …
=> Unfocus Remote Control Mode statusbar item on click

docs/Debugging/remote-control-mode.md, package.json
Add another way to press the home button when in Remote Control Mode.
- maps Ctrl+Escape (windows) or Cmd+Escape to the "Home" button.
Ctrl+Escape might be bound to a windows system key, but since you still have Shift+Home, it's no harm.
=> Allow Ctrl/Cmd + Escape for home press

src/LanguageServerManager.ts, src/LanguageServerRunner.ts
Sometimes when debugging the language server, our early breakpoints don't get hit. This seems to be related to vscode just running it before we can attach. To improve this, detect when we're in "Extension Host" mode, and add a 1.5s delay so it has time to attach properly. This has no effect when running in production mode (i.e. end-users won't get the delay applied).
=> Delay language server when running in dev mode

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Adds syntax highlighting support for the new `const` keyword. 
See https://github.com/rokucommunity/brighterscript/pull/632
=> Syntax highlighting support for the new `const` keyword

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Fixes an issue with import keyword not coloring with 0 or 2+ spaces
=> Better import statement syntax highlighting.

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Fix syntax highlighting bug in property use and function calls.
**Before:**:
Notice the `isLoggedIn` is colored weird, and the `andDogs` is totally white (meaning it wasn't tokenized at all).
**After:**
=> Fix property and call syntax highlighting

images/icons/brighterscript.svg, images/icons/brightscript.svg, package-lock.json, package.json
Adds custom file icons for .bs and .brs files. 
Note that the brightscript icon is slightly wider than most other icons. I thought it was important to show the lowercase `r` to better visualize that this was a non-brighterscript file.
=> Add .bs and .brs file icon support

syntaxes/brightscript.tmLanguage.json
ease the import of brightscript.tmLanguage.json in eclipse+tm4e
=> add "bs" as "fileTypes" element

src/ActiveDeviceManager.ts
Fixes issue with the "Devices" panel that was not always finding devices whenever the developer machine has multiple active network interfaces.
=> Improve multi-network-interface device discovery

package-lock.json, package.json, src/LogOutputManager.spec.ts, src/LogOutputManager.ts, src/extension.spec.ts, src/extension.ts, src/util.ts, src/viewProviders/RendezvousViewProvider.ts
Support for refactored custom events from roku-debug. 
Depends on: 
- https://github.com/rokucommunity/roku-debug/pull/103
- https://github.com/rokucommunity/roku-deploy/pull/96
=> Handle new custom event structures and names

src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts, src/LanguageServerManager.spec.ts, src/mockVscode.spec.ts
When #438 was released, it started flooding the debug session configs with all of the default launch.json values, even if the user hadn't set any of them. This PR fixes that by only merging in the `brightscript.debug` settings that were explicitly defined by the user. 
This PR also suppresses the "Could not load bsconfig file at..." error whenever the default file could not be loaded. Now it will only be shown if the user specifically defined a `configFile` value in their settings.
=> Ignore default user settings not set by user

docs/extension-settings.md, package.json, src/ActiveDeviceManager.ts, src/util.spec.ts, src/util.ts, src/viewProviders/OnlineDevicesViewProvider.ts
Adds an option to obfuscate (scramble/obscure) the device-info for items in the device panel. 
The option is named `brightscript.deviceDiscovery.concealDeviceInfo`.
Here are the fields that get redacted.
=> Add option to obscure the device-info

package.json, src/extension.ts, src/viewProviders/RendezvousViewProvider.ts
Allow the rendezvous panel to be cleared even when there's no active debug session. 
Also moved the "clear" button out to an icon on the bar instead of hiding it inside the menu.
Current:
Proposed:
=> Allow clearRendezvous cmd outside a debug session

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Fix syntax highlighting for `continue for` and `continue while`. 
**Before:**
**After:**
=> fix: continue keyword colorization

src/DebugConfigurationProvider.ts
Ran into this issue on a new install of an existing project.
injectRale was set, setting was non-existent and error VS Code gave was...less than helpful.
=> Added validation for raleTrackerTaskFileLocation setting existence.

package-lock.json, package.json, src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts, src/extension.ts, src/mockVscode.spec.ts
- Fixes an issue during launch that would crash if `injectRaleTrackerTask` was true, but no tracker task path was specified. 
- wraps the entire launch config sanitization in a try/catch so we can write any exception to the output channel
=> Fix crash during launch due to missing rale option

package-lock.json, package.json, webviews/src/views/RokuDeviceView/RokuDeviceView.svelte, webviews/src/views/SceneGraphInspectorView/Branch.svelte, webviews/src/views/SceneGraphInspectorView/NodeDetailPage.svelte
• Switch from ChromeClose icon to ArrowLeft icon to avoid confusion when closing detail page 
• Remember last showKeyPathInfo to make accessing key path info easier]
• Switch to running findNodesAtLocation in webview directly
• switch to using keyPaths for key for expanded nodes
=> Run find node calculations in webview and other improvements

package-lock.json, package.json, src/BrightScriptCommands.ts
Fix runtime crash when inside vscode extension because request module was removed. Fixed by declaring postman-request as direct dependency and using that.
=> Fix crash by using postman-request instead of request

package-lock.json, package.json, src/LanguageServerManager.ts, src/commands/LanguageServerInfoCommand.ts
Shows a busy spinner in the statusbar anytime the language server is busy.
Depends on https://github.com/rokucommunity/brighterscript/pull/852 being released.
=> Show a spinner in the statusbar when lsp is busy

package-lock.json, package.json, src/DebugConfigurationProvider.ts
Adds `deleteDevChannelBeforeInstall` launch option, to resolve issues outlined in https://github.com/rokucommunity/roku-debug/pull/158
=> Add deleteDevChannelBeforeInstall launch option

package.json, src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts, src/extension.ts, src/managers/RemoteControlManager.ts
=> Enable remote control on launch

src/viewProviders/RokuAutomationViewViewProvider.ts
Fixes a behind-the-scenes crash in roku-automation-view when there is no config found.
(image of the crash before the fix)
=> Fix automation view crash when no config found

src/DebugConfigurationProvider.ts
Aligns the name of the device in the device picker with the name from the devices tree view panel by adding in the user-defined name. 
**Before:**
**After:**
=> Make device picker name same as tree view item

src/viewProviders/OnlineDevicesViewProvider.ts
Issue: https://github.com/rokucommunity/vscode-brightscript-language/issues/510
This adds the ability to open the ECP registry with just a click. There will be another addition following up to allow the user to pick which channel they want to choose.
=> Add link for ECP registry

src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts, src/GlobalStateManager.ts, src/constants.ts, src/extension.ts, src/managers/TelemetryManager.ts, src/mockVscode.spec.ts, src/util.ts
Auto-enables the debug protocol for any launch to a 12.5 devices that doesn't explicitly have `enableDebugProtocol` defined. 
We intend on running this as a trial period for a week to see what issues are uncovered. If the test goes smoothly, we'll leave this feature enabled indefinitely. If issues are discovered, we'll disable the protocol until we can fix the issues and then try again in the future. The goal of this is to tell the user we've enabled the protocol, but still give them an option for using telnet instead. However, it's in the user's best interest to give the debug protocol a thorough test, because it _will_ become the default debug mode in the near future. 
Users are presented with this popup:
Then after 2  clicks of the "Use telnet" button, we switch to this so the user can …
=> Auto-enable debug protocol on 12.5 devices

src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts
- Always show the "ask less often" option for telnet.
- change the debug protocol "ask less often" choice to 12 hours (was 2 weeks)
- add slight explanation about what debug protocol is
=> Better messaging around debugProtocol popup

src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts, src/mockVscode.spec.ts
- Sets a shorter timeout for the device-info query so the user isn't just stuck waiting forever wondering what's happening. 
- show a spinning statusbar item when device-info is being requested.
=> Shorten the timeout for device-info query

src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts, src/extension.ts, src/managers/UserInputManager.spec.ts, src/managers/UserInputManager.ts
Moves the `promptForHost` command into a `UserInputManager` class so we can start centralizing our user input flows and sharing them to unify the experience across the extension.
=> Move common user input into a dedicated manager

.vscode/tasks.json, scripts/watch-all.ts
Fix the problem matcher in the `watch-all` task when running the workspace. This is fixed by emitting absolute paths instead of relative paths, which then work for both the workspace and individual folders
=> Fix watch-all problem matcher and output

src/LanguageServerManager.ts
Fix a spelling mistake in the "Can't find language server" error message. 
Thanks @triwav for finding this!
=> Fix spelling mistake in lsp message

package.json
Adds a few missing `brightscript.debug` settings to user/workspace settings.
=> Add a few missing brightscript.debug settings

package.json, src/commands/VscodeCommand.ts, src/viewProviders/BaseWebviewViewProvider.ts, src/viewProviders/RokuDeviceViewViewProvider.ts, webviews/src/views/RokuDeviceView/RokuDeviceView.svelte
Some small improvements to screenshot capability to make it easier to share screenshots from device. Changed it to request an initial screenshot where as before if you didn't have continuous screenshot capture on it would not request any on its own unless you clicked refresh
=> Always request screenshot on initial load, add ability to copy screenshot

package-lock.json, package.json, src/LogOutputManager.ts
This change utilizes the modal property that was added to the `PopupMessageEvent`. The modal property is being added to make any errors more visible when VSCode fails to launch a channel. The most common example of this is a bad password.
Here's a screen shot of the modal.
=> Pass the modal property from the PopupMessageEvent

src/DebugConfigurationProvider.ts
Fixes a bug related to stagingDir and stagingFolderPath when `stagingDir` is also present in a root-level `bsconfig.json`
=> Sets `stagingDir` properly in DebugConfigurationProvider

package.json
Removes a duplicate command called `clearLogOutput` that was duplicated in the package.json for some reason.
=> Remove duplicate 'clearLogOutput' command

src/BrightScriptCommands.ts
Fixes an error when copying a numeric value to clipboard from the device panel
**Before:**
**After:**
=> Fix crash when trying to copy numeric values to the clipboard

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Fix syntax highlighting for conditional compile items with spaces between `#` and the next keyword.
**Before:**
**After:**
=> Fix conditional compile syntax highlighting

src/viewProviders/RokuFileSystemViewViewProvider.ts, src/viewProviders/ViewProviderCommand.ts, webviews/src/views/RokuFileSystemView/FileSystemEntry.svelte, webviews/src/views/RokuFileSystemView/RokuFileSystemView.svelte
=> Delete button in FS view

package.json, src/commands/VscodeCommand.ts, src/viewProviders/BaseWebviewViewProvider.ts, src/viewProviders/SceneGraphInspectorViewProvider.ts
This PR allows opening the SceneGraph Inspector as a WebViewPanel in the current window. As of the April 2024 release of Visual Studio Code, you can also move that panel from the current window to a new window as well although there is currently no way to programmatically do this.
=> Add support for opening SceneGraph Inspector in panel

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Adds syntax highlighting for the [alias statement](https://github.com/rokucommunity/brighterscript/pull/1151) coming in v1.
Before:
After:
=> Adds syntax highlighting for `alias` statements

docs/Editing/error-handling.md
Fixes incorrect docs related to the `bs:disable-line` comment.
=> Fix incorrect brs:disable-line docs

src/LanguageServerManager.spec.ts, src/LanguageServerManager.ts
Whenever the language server crashes, vscode will restart it. After the 5th crash, they'll leave it permanently crashed. There seems to be no time limit on adding up to the 5, so even after a few days, vscode may still terminate the language server. 
This PR adds tracking for when language server is stopped and then not started back up again after a period of time.
For example, 20 seconds after after the final failure, this event fires so that we can show a "wanna restart it" popup.
=> Prompt to restart lsp if it has stopped

src/LanguageServerManager.spec.ts, src/LanguageServerManager.ts, src/managers/WebviewViewProviderManager.spec.ts, src/mockVscode.spec.ts
Fix a bug in the lsp crash tracker.
=> Fix lsp crash tracker

webviews/src/ExtensionIntermediary.ts, webviews/src/views/SceneGraphInspectorView/Branch.svelte
=> Add support for removing nodes in SceneGraph Inspector

webviews/src/views/SceneGraphInspectorView/NodeCountByTypePage.svelte, webviews/src/views/SceneGraphInspectorView/SceneGraphInspectorView.svelte
As you can see in the preview not all nodes are not available to view. This is because those nodes are not currently stored. This could potentially be added in the future but would be a good deal of work to support.
=> Add support for viewing nodes that are in the node tree from NodeCountByTypePage

docs/extension-settings.md, package.json
I saw this option missing - is this all it takes to make it available?
=> Sort imports setting

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Adds support for syntax highlighting of bsdoc tags and types.
=> Add syntax highlighting support for bsdoc tags

src/BrightScriptCommands.ts, src/DebugConfigurationProvider.ts, src/DeclarationProvider.ts, src/LanguageServerManager.ts, src/commands/LanguageServerInfoCommand.ts
Fix several spots where workspaceFolders was not being safely accessed, since it can sometimes be `undefined`.
Originally reported in #588
=> Fix crashes where workspaceFolders was undefined

package.json, src/BrightScriptCommands.ts, src/viewProviders/OnlineDevicesViewProvider.ts
Add feature to be able to set a device as the current active device via the Device tree view.
Also added command to clear the active device.
=> Add feature to be able to set a device as the current active device via the Device tree view. Also added command to clear the active device.

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Fixes syntax highlighting bug related to `.top`
Before:
After:
=> Fix bug with m.top colorization

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Fixes https://github.com/rokucommunity/vscode-brightscript-language/issues/411 syntax highlighting for the `as` keyword in function return types when a parameter is also of type `function`
**Before:**
**After (notice the `as` is purple now):**
=> Syntax highlighting but for object functions

src/LanguageServerManager.spec.ts, src/LanguageServerManager.ts
Fixes a bug when the busy spinner has run too long, it would show _many_ console logs instead of 1 at the end. This fixes that.
=> Fix issues with busy spinner showing too many error messages

package-lock.json, package.json, src/BrightScriptCommands.ts, src/LogOutputManager.ts
Retain the original newlines in the `BrightScript Log` output panel that were sent from the device (we had some if statements excluding them). Also strip ansii colors from the output panel because they're very ugly and not supported.
=> Retain original newlines in BrightScript Log output panel, and also strip ansii colors

src/DebugConfigurationProvider.ts
Reenable the `deferScopeLoading` launch option now that the underlying crash has been fixed.
=> Reenable the `deferScopeLoading` launch option

docs/Debugging/remote-control-mode.md, package.json
When using the remote control mode the navigation keys `PageUp` and `PageDown` were mapped to `FF` and `Rewind` respectively, that causes inverted behavior when navigating in `LabelList` and `CheckList` nodes for instance, when you press `PageDown` instead of going down in the list it goes up.
This PR inverts the behavior to be in the way any user would expect.
=> Inverted keys `PageUp` and `PageDown` mapping on remote control mode

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
Fixes bug: https://github.com/rokucommunity/vscode-brightscript-language/issues/633
Adds "return-and-type" to test bsdoc for syntax highlighting on {return|returns}
=> bsdoc return and type syntax highlighting

src/grammar/brightscript.tmLanguage.spec.ts, syntaxes/brightscript.tmLanguage.json
This PR adds syntax highlighting to inline comments made on enum fields, see bug for more details --> https://github.com/rokucommunity/vscode-brightscript-language/issues/362
=> bugfix enum field inline comment syntax highlighting

src/managers/TelemetryManager.ts
Add telemetry tracking for the `bsConst` entry in launch.json
=> Track bsConst telemetry usage in launch.json

.github/workflows/make-release-artifacts.yml
Release 2.56.0 failed to upload any artifacts because the artifact-paths was incorrectly looking for `*.tgz`. This fixes the issue by looking for `*.vsix`
=> chore: fix incorrect artifact-paths for creating releases

package.json
- Adds `brighscript.projects`, see https://github.com/rokucommunity/brighterscript/pull/1521
- Removes `brightscript.configFile`
- Adds `brightscript.enableProjectDiscovery`, see https://github.com/rokucommunity/brighterscript/pull/1520
=> Settings schema update to support recent lsp changes

docs/variable-substitutions.md, package.json, src/DebugConfigurationProvider.spec.ts, src/DebugConfigurationProvider.ts, src/extension.ts
This PR introduces a new variable substitution, `${activeHost}`, that allows users to dynamically reference the currently configured remote host in their debug configurations.
In addition, I added a small documentation about this variable substitution functionality, which may help others identify their goal.
🚀 Why
- Enables more flexible debug configurations that can adapt to different remote hosts
- Reduces the need to manually update host references across multiple configuration files
=> Add new launch variable substitution called `activeHost`
